### ISSUE TITLE
Pasted Text Does Not Appear on Top of Clipboard History

### ISSUE THREAD

**Issue by OTAKUWeBer** [Zai-Kun/rustyclip#1]
Issue: 
https://github.com/user-attachments/assets/445c33c2-c7f8-4c63-a3a3-b3657a844773

**Description:**
When copying text, it gets pasted correctly, but the copied word doesn't appear at the top of the clipboard history. The clipboard history does not reflect the most recent copy action, causing the newly copied text to appear further down in the history list.

**Steps to Reproduce:**
1. Copy text.
2. Copy additional text after the first.
3. Paste the most recently copied text.
4. Observe that the copied word does not appear at the top of the clipboard history.

**Expected Behavior:**
The most recently copied text should always appear at the top of the clipboard history.

**Actual Behavior:**
The most recently copied text does not appear at the top of the clipboard history.

**Comment by OTAKUWeBer** [comment]
It would be better if the clipboard history starts from index 1 instead of 0.

**Comment by Zai-Kun** [comment]
Working on it.
